name: Swift
env:
    XCODE_VERSION: "latest-stable"
on:
  push:
  pull_request:
jobs:
  swift-build:
    runs-on: macos-15 # macos-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - name: Install Metal Toolchain
        run: xcodebuild -downloadComponent MetalToolchain
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: swift build -v
      - run: swift test -v
